"""add updated_at to reports

Revision ID: 0fe4bdd1b9a7
Revises: 78ae0eeca9dd
Create Date: 2026-06-27 11:23:33.679925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe4bdd1b9a7'
down_revision: Union[str, None] = '78ae0eeca9dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'reports',
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'updated_at')
    # ### end Alembic commands ###
