"""init: create 9 core tables

Revision ID: 2a3dd7b2d3e0
Revises: 
Create Date: 2026-05-12 23:25:19.733723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3dd7b2d3e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('invite_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_index('idx_invite_code', 'families', ['invite_code'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('blood_type', sa.Enum('A', 'B', 'AB', 'O', name='blood_type_enum'), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('chronic_diseases', sa.JSON(), nullable=False),
    sa.Column('type', sa.Enum('adult', 'child', 'elderly', name='member_type_enum'), nullable=False),
    sa.Column('role', sa.Enum('creator', 'member', name='member_role_enum'), nullable=False),
    sa.Column('wx_openid', sa.String(length=100), nullable=True),
    sa.Column('subscription_status', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_member_family', 'members', ['family_id'], unique=False)
    op.create_index('idx_member_wx_openid', 'members', ['wx_openid'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('page_context', sa.String(length=50), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_conv_member_updated', 'ai_conversations', ['member_id', 'updated_at'], unique=False)
    op.create_table('health_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('visit', 'lab', 'medication', 'symptom', 'ai', 'hospital', 'vaccine', 'checkup', 'milestone', name='health_event_type_enum'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('hospital', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('doctor', sa.String(length=50), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('normal', 'abnormal', name='health_event_status_enum'), nullable=False),
    sa.Column('abnormal_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_event_member_date', 'health_events', ['member_id', 'event_date'], unique=False)
    op.create_index('idx_health_event_type', 'health_events', ['type'], unique=False)
    op.create_table('hospital_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('hospital', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=False),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('diagnosis', sa.String(length=200), nullable=True),
    sa.Column('doctor', sa.String(length=50), nullable=True),
    sa.Column('key_nodes', sa.JSON(), nullable=False),
    sa.Column('watch_indicators', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('active', 'discharged', name='hospital_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hospital_member_status', 'hospital_events', ['member_id', 'status'], unique=False)
    op.create_table('indicator_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('indicator_key', sa.String(length=50), nullable=False),
    sa.Column('indicator_name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('lower_limit', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('upper_limit', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('status', sa.Enum('normal', 'low', 'high', 'critical', name='indicator_status_enum'), nullable=False),
    sa.Column('deviation_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('source_report_id', sa.String(length=36), nullable=True),
    sa.Column('source_hospital_id', sa.String(length=36), nullable=True),
    sa.Column('source_batch_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_indicator_member_date', 'indicator_data', ['member_id', 'record_date'], unique=False)
    op.create_index('idx_indicator_member_key_date', 'indicator_data', ['member_id', 'indicator_key', 'record_date'], unique=False)
    op.create_index('idx_indicator_status', 'indicator_data', ['status'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('vaccine', 'checkup', 'review', 'medication', name='reminder_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'overdue', name='reminder_status_enum'), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('related_indicator', sa.String(length=50), nullable=True),
    sa.Column('related_report_id', sa.String(length=36), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'normal', 'low', name='reminder_priority_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminder_member_status', 'reminders', ['member_id', 'status'], unique=False)
    op.create_index('idx_reminder_scheduled', 'reminders', ['scheduled_date'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('lab', 'diagnosis', 'prescription', 'discharge', name='report_type_enum'), nullable=False),
    sa.Column('hospital', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('extracted_indicators', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('ocr_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='ocr_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_member_date', 'reports', ['member_id', 'report_date'], unique=False)
    op.create_table('vaccine_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('vaccine_name', sa.String(length=100), nullable=False),
    sa.Column('dose', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('completed', 'pending', 'upcoming', 'overdue', name='vaccine_status_enum'), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('batch_no', sa.String(length=50), nullable=True),
    sa.Column('reaction', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vaccine_member_status', 'vaccine_records', ['member_id', 'status'], unique=False)
    op.create_index('idx_vaccine_scheduled', 'vaccine_records', ['scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vaccine_scheduled', table_name='vaccine_records')
    op.drop_index('idx_vaccine_member_status', table_name='vaccine_records')
    op.drop_table('vaccine_records')
    op.drop_index('idx_report_member_date', table_name='reports')
    op.drop_table('reports')
    op.drop_index('idx_reminder_scheduled', table_name='reminders')
    op.drop_index('idx_reminder_member_status', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('idx_indicator_status', table_name='indicator_data')
    op.drop_index('idx_indicator_member_key_date', table_name='indicator_data')
    op.drop_index('idx_indicator_member_date', table_name='indicator_data')
    op.drop_table('indicator_data')
    op.drop_index('idx_hospital_member_status', table_name='hospital_events')
    op.drop_table('hospital_events')
    op.drop_index('idx_health_event_type', table_name='health_events')
    op.drop_index('idx_health_event_member_date', table_name='health_events')
    op.drop_table('health_events')
    op.drop_index('idx_ai_conv_member_updated', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index('idx_member_wx_openid', table_name='members')
    op.drop_index('idx_member_family', table_name='members')
    op.drop_table('members')
    op.drop_index('idx_invite_code', table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
