"""add vaccine_library table

Revision ID: 78ae0eeca9dd
Revises: dfed678dc90d
Create Date: 2026-06-26 23:53:55.473663

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78ae0eeca9dd'
down_revision: str | None = 'dfed678dc90d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine_library',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dose_number', sa.Integer(), nullable=False),
    sa.Column('recommended_age_months', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vaccine_lib_age', 'vaccine_library', ['recommended_age_months'], unique=False)
    op.create_index('idx_vaccine_lib_name_dose', 'vaccine_library', ['name', 'dose_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vaccine_lib_name_dose', table_name='vaccine_library')
    op.drop_index('idx_vaccine_lib_age', table_name='vaccine_library')
    op.drop_table('vaccine_library')
    # ### end Alembic commands ###
