"""add growth_records table

Revision ID: dfed678dc90d
Revises: e5686824a889
Create Date: 2026-06-26 22:28:21.943932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfed678dc90d'
down_revision: Union[str, None] = 'e5686824a889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growth_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_growth_member_type', 'growth_records', ['member_id', 'record_type'], unique=False)
    op.create_index('idx_growth_recorded_at', 'growth_records', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_growth_recorded_at', table_name='growth_records')
    op.drop_index('idx_growth_member_type', table_name='growth_records')
    op.drop_table('growth_records')
    # ### end Alembic commands ###
